/**
 * regen_baseline.mjs — regenerate tools/gate/wall_baseline.json.
 *
 * THIS IS THE ONLY WAY THE BASELINE CHANGES. The gate itself never writes it.
 *
 * Regenerating the baseline is how you make this gate stop complaining, so the
 * act is deliberately loud and deliberately inconvenient:
 *
 *   1. It is a separate npm script (`npm run gate:baseline`) — `npm run gate`
 *      can never reach this code path.
 *   2. It requires an explicit --i-am-changing-the-baseline flag, so it cannot
 *      be run by accident or by a wrapper script that "just fixes things".
 *   3. It prints a full added/removed/deepened diff to stdout before writing.
 *   4. The output is pretty-printed, key-sorted JSON, so the resulting git diff
 *      is human-readable line-by-line in review.
 *
 * Usage:
 *   npm run gate:baseline -- --i-am-changing-the-baseline
 *
 * This file MUST NOT use  2>/dev/null  or  || true .
 */

import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { buildHeadlessScene } from './scene.mjs';
import { runPlacementAudit }  from '../../src/dev/placement_audit.ts';

const HERE = dirname(fileURLToPath(import.meta.url));
const BASELINE_PATH = join(HERE, 'wall_baseline.json');
const FLAG = '--i-am-changing-the-baseline';

if (!process.argv.includes(FLAG)) {
  console.error('regen_baseline: refusing to run without an explicit flag.');
  console.error('');
  console.error('Regenerating the baseline silences the wall-placement gate for');
  console.error('every mesh currently intersecting a wall. If a prop is genuinely');
  console.error('buried in a wall right now, regenerating will bless that bug.');
  console.error('');
  console.error('If you are sure the current scene is correct, run:');
  console.error(`  npm run gate:baseline -- ${FLAG}`);
  process.exit(2);
}

// ── Build scene and take a fresh census ──────────────────────────────────────

console.log('regen_baseline: building headless scene…');
const { roots } = buildHeadlessScene();

// Pass an empty baseline: we want the raw census, not a comparison.
const fresh = runPlacementAudit(roots, []);

const rows = [...fresh.census].sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));

// ── Diff against the existing baseline, if any ───────────────────────────────

/** @type {{entries: {key:string,depth:number,face:string,name:string,why:string}[]}} */
let old = { entries: [] };
if (existsSync(BASELINE_PATH)) {
  old = JSON.parse(readFileSync(BASELINE_PATH, 'utf8'));
}
const oldByKey = new Map(old.entries.map((e) => [e.key, e]));
const newKeys  = new Set(rows.map((r) => r.key));

const added    = rows.filter((r) => !oldByKey.has(r.key));
const removed  = old.entries.filter((e) => !newKeys.has(e.key));
// Compare at the precision the baseline is actually stored at (6dp). Comparing
// raw floats against rounded stored values reports every row as "deepened" by
// sub-nanometre noise, which would train reviewers to skim past the diff — the
// one thing this diff exists to prevent.
const storedDepth = (d) => Number(d.toFixed(6));
const deepened = rows.filter((r) => {
  const e = oldByKey.get(r.key);
  return e !== undefined && storedDepth(r.depth) > e.depth;
});

console.log('');
console.log(`Baseline diff: +${added.length} added, -${removed.length} removed, ` +
            `${deepened.length} deepened`);
for (const r of added)   console.log(`  [+] ${r.name.padEnd(18)} ${r.face} depth=${r.depth.toFixed(3)} ${r.key}`);
for (const e of removed) console.log(`  [-] ${e.name.padEnd(18)} ${e.face} depth=${e.depth.toFixed(3)} ${e.key}`);
for (const r of deepened) {
  const e = oldByKey.get(r.key);
  console.log(`  [~] ${r.name.padEnd(18)} ${r.face} depth ${e.depth.toFixed(3)} -> ${r.depth.toFixed(3)}`);
}

// ── Write ────────────────────────────────────────────────────────────────────
// Preserve any hand-written `why` from the previous baseline so review notes
// are not lost on regeneration; new rows get a placeholder that reviewers can
// grep for.

const entries = rows.map((r) => ({
  key:   r.key,
  depth: Number(r.depth.toFixed(6)),
  face:  r.face,
  name:  r.name,
  why:   oldByKey.get(r.key)?.why ?? 'REGENERATED — justify this row in review',
}));

const doc = {
  _comment: [
    'Baseline census of every mesh whose world AABB intersects a wall slab.',
    'Generated by tools/gate/regen_baseline.mjs; never edited by the gate.',
    'A mesh not listed here that touches a wall is reported as WALL-NEW.',
    'A listed mesh that penetrates deeper than `depth` is reported as WALL-DEEPER.',
  ],
  generatedBy: 'tools/gate/regen_baseline.mjs',
  entryCount: entries.length,
  entries,
};

writeFileSync(BASELINE_PATH, JSON.stringify(doc, null, 2) + '\n', 'utf8');

console.log('');
console.log(`regen_baseline: wrote ${entries.length} entries to ${BASELINE_PATH}`);
console.log('Review the git diff of that file before committing.');
